/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;

/**
 *
 * @author Khoa
 */
public class ShowJFrame extends javax.swing.JFrame {
    public BufferedImage Bi;
    /**
     * Creates new form MainJFrame
     */
    public ShowJFrame() {
        //add(new JTextField());
        initComponents();        
        //System.out.println("test");
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.addKeyEventDispatcher(new MyDispatcher());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        imgPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        imgPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        imgPanel.setHorizontalScrollBar(null);
        imgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imgPanelMouseReleased(evt);
            }
        });
        imgPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                imgPanelMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPanelMouseEntered
        // TODO add your handling code here:
        //System.out.println("start: " + evt.getX() + ":" + evt.getY());
    }//GEN-LAST:event_imgPanelMouseEntered

    private void imgPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPanelMouseExited
        // TODO add your handling code here:
//        System.out.println("end: " + evt.getX() + ":" + evt.getY());
    }//GEN-LAST:event_imgPanelMouseExited

    private void imgPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPanelMouseDragged
        // TODO add your handling code here:
        //System.out.println("drag: " + evt.getX() + ":" + evt.getY());
        //this.repaint();
    }//GEN-LAST:event_imgPanelMouseDragged

    private void imgPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPanelMousePressed
        // TODO add your handling code here:
        //System.out.println("start: " + evt.getX() + ":" + evt.getY());
    }//GEN-LAST:event_imgPanelMousePressed

    private void imgPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPanelMouseReleased
        // TODO add your handling code here:
        //System.out.println("end: " + evt.getX() + ":" + evt.getY());
    }//GEN-LAST:event_imgPanelMouseReleased

    private class MyDispatcher implements KeyEventDispatcher {

        @Override
        public boolean dispatchKeyEvent(KeyEvent e) {
            if (e.getID() == KeyEvent.KEY_PRESSED) {
                //System.out.println(e.getID());
                //System.out.println("------------");
            }
            return false;
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane imgPanel;
    // End of variables declaration//GEN-END:variables
}
